데이터베이스 접근 로직
hegunhee/fastcampus-project-board pull request #10
Opened 2024-10-01 14:14 UTC by hegunhee

더이상 사용하지않는 h2-console 설정을 삭제했습니다.
Auditing 프로퍼티들을 하나의 클래스로 만들어 AuditingFields 클래스를 만들었습니다.

예제 코드와는 다르게 AuditingFields클래스를 abstract로 작성했습니다.
해당 클래스는 단독 객체로 존재할 수 없기때문에 abstract로 만들었습니다.

This closes #9

2024-10-03 20:35 UTC, mikonu reviewed
수고하셨습니다.

2024-10-03 20:35 UTC, mikonu commented on src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
> +public class ArticleComment extends AuditingFields{
```suggestion
public class ArticleComment extends AuditingFields {
```

2024-10-03 20:35 UTC, mikonu commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +public class Article extends AuditingFields{
```suggestion
public class Article extends AuditingFields {
```

2024-10-03 20:35 UTC, mikonu commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +public class Article extends AuditingFields{
제안 코드를 깃헙을 이용해 바로 커밋하는 방법을 여기서 한 번 시도해 보세요.

2024-10-03 20:35 UTC, mikonu commented on src/main/java/com/fastcampus/projectboard/domain/AuditingFields.java
> +    private LocalDateTime createdAt;
이 접근자 `private`는 사실 이슈가 있습니다. 무엇일지 생각해 보세요.

2024-10-05 01:09 UTC, hegunhee commented
해당 브랜치의 경우 커밋 메시지 수정때문에
origin branch -> local branch로 머지되었음
해당 브랜치가 squash머지될 때 확인해보면 좋을 듯함

2024-10-06 07:30 UTC, hegunhee commented
[7ea9f85](https://github.com/hegunhee/fastcampus-project-board/pull/10/commits/7ea9f8543b5aeb2efe415f356b255c194bfaef97) 해당 커밋에서 AuditingFields클래스의 equals와 hashcode를 구현했으나
해당 설계는 자식클래스가 부모 클래스에 의존적이게 되는 상황을 발생시킵니다.
중복 코드를 삭제해줄 수 있다는 장점이 존재하지만. 부모 클래스에 의존하는게 단점입니다.

2024-10-08 16:27 UTC, mikonu reviewed
`AuditingFields`의 각 멤버들을 자식클래스에서 비교할 때 일어나는 코드 중복을 피하고자 하는 시도 잘 봤습니다. 이 방식이 의도대로 동작하는지? 그것을 어떻게 증명할 수 있는지? 보여주는 테스트 코드가 있다면 이 pr이 훨씬 설득력있고 강한 코드가 될 수 있습니다. 팀에 새로운 기술을 보여줄 때는 이 점을 꼭 고려해 주시고요, 실제로 이 코드가 의도대로 잘 동작할지도 한 번 생각해 봅시다.

2024-10-08 16:27 UTC, mikonu commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            AuditingFields thisAuditingField = this;
이 부분 뭔가 이상하네요. 의도대로 동작할까요?

2024-10-08 16:27 UTC, mikonu commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            return Objects.hash(getTitle(), getContent(), getHashtag(),super.hashCode());
```suggestion
            return Objects.hash(getTitle(), getContent(), getHashtag(), super.hashCode());
```

2024-10-08 16:27 UTC, mikonu commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            return Objects.hash(getTitle(), getContent(), getHashtag(),super.hashCode());
해시코드의 입력 파라미터에 부모 클래스가 이미 작성한 해시코드를 다시 넣는 형태네요. 이러한 방법은 문제가 없을까요?

cc. @zhdiddl 함께 살펴봐 주세요.

2024-10-09 00:04 UTC, hegunhee commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            AuditingFields thisAuditingField = this;
테스트코드를 작성해보겠습니다. (equals 테스트를 위해 컬렉션에 넣고 검증해보는 방식으로 테스트해보겠습니다.)
AuditingFields의 equals의 경우 자기 자신에 대한 검증이 없기때문에 확인해봐야될것같습니다.

2024-10-09 00:31 UTC, hegunhee commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            AuditingFields thisAuditingField = this;
컬렉션에 영속상태가 아닌 Article 객체를 여러개 넣어서 비교하는 테스트코드를 작성해보겠습니다!

2024-10-09 00:57 UTC, hegunhee commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            return Objects.hash(getTitle(), getContent(), getHashtag(),super.hashCode());
hashcode 함수의 명세를 보고 문제점을 확인했습니다.
hashcode 함수는 파라미터의 모든 값의 hashcode를 계산해서 31을 곱한다음 다시 더하게 되는데요
super.hashcode는 이미 hashcode 계산값인데 거기다 또 31을 곱하게 됩니다.

그러므로 hashcode의 값이 불필요하게 커지는 결과를 만들게됩니다.
이 부분은 테스트코드 작성과 함께 같이 테스트해서 반영하겠습니다.

작업 순서 공유하겠습니다.
1. 현재 작업한 코드를 배경으로 테스트코드 작성
2. 문제가 있다면 equals, hashcode 함수 하나씩 변경하면서 테스트 수행
3. 테스트코드에 문제가 없다면 커밋

2024-10-09 01:11 UTC, hegunhee commented on src/main/java/com/fastcampus/projectboard/domain/AuditingFields.java
> +    private LocalDateTime createdAt;
추상클래스의 경우 자식 클래스에게 접근제어자를 열어주는것이 관례입니다.

2024-10-09 12:43 UTC, hegunhee commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            AuditingFields thisAuditingField = this;
@mikonu 자기 자신으로 캐스팅하더라도 인스턴스는 Article이기 때문에
thisAuditingFields.equals는 Article의 equals를 호출합니다... 그렇기때문에 stackoverflow를 발생시킵니다

2024-10-09 12:53 UTC, hegunhee commented on src/main/java/com/fastcampus/projectboard/domain/Article.java
> +            return Objects.hash(getTitle(), getContent(), getHashtag(),super.hashCode());
```java
return Objects.hash(getTitle(), getContent(), getHashtag(),super.hashCode());
```
해당 코드의 문제는 다음과 같습니다.
Obects.hash 함수의 경우 인자들의 hashcode 값을 다시 계산해서 결과값에 더하는 방식입니다.

위의 코드에서 super.hashcode()값으로 결과를 계산했는데 해당 값을 hashcode를 한번 더 호출한다고 생각하시면 됩니다.
중복으로 계산할 필요가 없기때문에 super.hashcode를 밖으로 빼서 더하는 방식으로 수정하겠습니다.

2024-10-10 00:05 UTC, mikonu requested changes
`TestArticle`의 작성과 그 테스트로 `equals()`, `hashcode()` 테스트가 시작되었습니다. 좋은 일이지만 이 작업은 #9 와는 다소 무관한 기술적 논의입니다. 때문에 #9 작업의 집중도가 낮아지고 다음 작업으로 진행하기 어려운 문제를 만든 것 같습니다. 그러면 전체 개발 일정에도 영향을 주게 될 것입니다. 이 코드들이 여기서 pr을 통해 제품에 반영되는 것이 좋을지 생각해 봅시다. 저는 이 추가된 코드와 작업이 별도의 이슈로 분리된다면 더 좋겠습니다.

여기서 새로운 문제를 별도 이슈로 분리하여 연구하면서, 제품 개발도 진행해서 일정에 차질이 없게 하려면 어떻게 하면 좋을지를 고민해 봅시다.

2024-10-10 00:40 UTC, hegunhee commented
#9 브랜치의 원래 하려던 작업이 아닌 AuditingFields 작업을 시작하는 부분부터 새로운 브랜치를 만들어서 작업을 해야했습니다.

지금이라도 브랜치를 분리해서 #9 브랜치에서 새로 만들어진 메타데이터 중복 제거 브랜치에 머지를 시켜서 작업완료 해놓겠습니다.

감사합니다.

2024-10-10 00:58 UTC, hegunhee commented
#19 issue를 기반으로 브랜치를 만들었습니다.
#10 브랜치의 AuditingFields 최적화 부분부터 리베이스 머지를 했지만
#10 입장에서는 #20 브랜치에서 변한것이 없기때문에 #10 <- #20 PR에 변경된 파일이 없다고 감지됩니다.

#20에서 AuditingFields 최적화 작업 전부터 후까지 rebase하고
#10 브랜치에서는 hard reset을 통해 AuditingFields 변경점을 삭제했습니다.

그러므로 #10 브랜치를 local에 불러오셨다면 반드시 pull후 작업해주시면 감사하겠습니다.

2024-10-10 08:17 UTC, mikonu approved these changes
수고하셨습니다. pr이 좀 더 `AuditingFields`와 h2 콘솔 빼는 것에 집중된 형태로 바뀌었네요. 이 역시도 여전히 2개 pr로 나눌 수 있지만 이는 강의 pr을 참고한 것이니 감안할 수 있겠고요. 강의 pr도 2가지 작업 주제가 하나의 pr에 섞인 경우를 체험하기 위한 의도가 담겨있었으니 여기서 그런 점이 잘 연습되셨을 거라 느껴집니다. 고생하셨습니다.

2024-10-16 02:01 UTC, merged